version: '2.1'
orbs:
  go: circleci/go@1.7.3
jobs:
  build:
    executor:
      name: go/default
      tag: '1.20'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: go test ./...
workflows:
  main:
    jobs:
      - build