version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.20
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/lruggieri/daily-coding-problems
    steps:
      - checkout

      - run: go mod vendor
      - run: go test -v ./...